# Generated by Django 3.2 on 2022-05-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220522_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
    ]
