# Generated by Django 3.2 on 2022-05-22 19:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
